name: Angular CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Git credentials
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular project
        run: npm run build -- --base-href="/thegarbagegame-webapp/"

      - name: Put build output in the root of 'current'
        run: |
          git fetch origin current
          git checkout current || git checkout -b current  # Create the branch if it doesn't exist

          # Remove the existing contents of the dist directory (optional)
          rm -rf *

          git checkout main -- dist/the-garbage-game/browser

          # Move the contents of dist/the-garbage-game/browser to the root
          mv ./dist/the-garbage-game/browser/* .

      - name: Commit build output
        run: |
          git add .
          git commit --allow-empty -m "Deploy Angular build output"
          git push origin current
